### ISSUE TITLE
有个字错了

### ISSUE THREAD

**Issue by liwei228407354** [axzxs2001/DengDengGui#2]
### 文章: 高效程序员的45个习惯.json的第七条
原文:
7、懂得丢弃": "学习新东西，丢弃旧的东西。在学习一门新技术的时候，要丢弃会**阴止**你前进的旧习惯。毕竟，汽车比马车车厢强得多",

应该将加粗部分的词**阴止**修改成 **阻止**

**Comment by axzxs2001** [comment]
谢谢
